spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&charactEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.oaec.springbootmp.entity
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.oaec.springbootmp.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
logging:
  level:
    com.oaec.springbootmp.mapper: trace
server:
  port: 8888
